### ISSUE TITLE
Access to LibSharedMedia for Fonts

### ISSUE THREAD

**Issue by boktai1000** [drzewieckinicholas/ChatFramePlus#17]
https://legacy.curseforge.com/wow/addons/chatframeplus?comment=1

Is there a way to pick up fonts from LibSharedMedia? At least when I installed it on SoD, I lost access to multiple fonts I have installed, such as Calibri which is basically a requirement for me.

Great addon though, I'm removing the chat tab backgrounds as I was unaware how to do this in Prat 3.0. Thank you!

**Comment by drzewieckinicholas** [comment]
Thanks @boktai1000

I saw your comment on CurseForge. I'll take a look into this issue when I have time this week. Should be doable as I was playing around with LibSharedMedia fonts early in development.

**Comment by drzewieckinicholas** [comment]
Although not exactly what you asked for, I've added a feature where you can provide up to 3 custom fonts in `ChatFramePlus\Assets\Fonts` and then select them in-game.

So if you're on Windows, you could copy `calibri.ttf` from `C:\Windows\Fonts\Calibri` to  `ChatFramePlus\Assets\Fonts` and re-name it to `custom-font-1.ttf`.

When I have a bit more time, I'll look into LibSharedMedia fonts. I tried implementing them but ran into some visual issue with the dropdown that was bothering me.
